export const home = "/";
export const login = "/login/";
export const organizationList = "/organization";
export const chargetpointList = "/chargetpoint";
export const organizationbyid = "/organization/:id";
export const organizationnew = "/organization/new";
export const chargetpointnew = "/chargetpoint/new";
export const organizationof = (id) => "/organization/" + id;
export const chargetpointof = (id) => "/chargetpoint/" + id;
export const editorganizationof = (id) => "/organization/" + id + "/edit";
export const editchargetpointof = (id) => "/chargetpoint/" + id + "/edit";
